// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0beeP374fE9LwehPVvO9o0Qnw2qyfu6M',
    appId: '1:801429879797:web:72197cb471af79ac843ebc',
    messagingSenderId: '801429879797',
    projectId: 'examenu2-689e7',
    authDomain: 'examenu2-689e7.firebaseapp.com',
    storageBucket: 'examenu2-689e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMq0WReJDF-lZ0Tz9wl2C2UtIj4v3itCM',
    appId: '1:801429879797:android:91b1e46cd1effec7843ebc',
    messagingSenderId: '801429879797',
    projectId: 'examenu2-689e7',
    storageBucket: 'examenu2-689e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPLUpKyLIMcoG2L77HcsuCGnn1c9ZRHLI',
    appId: '1:801429879797:ios:854d66d9b6529b3e843ebc',
    messagingSenderId: '801429879797',
    projectId: 'examenu2-689e7',
    storageBucket: 'examenu2-689e7.firebasestorage.app',
    iosBundleId: 'com.example.examenu2',
  );
}
